name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
            VITE_SUPABASE_URL: https://rqkatzjznnkosczbckdt.supabase.co

                            VITE_SUPABASE_PUBLISHABLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxa2F0empubmtvc2N6YmNrZHQiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTczMzIxODM1MywiZXhwIjoyMDQ4Nzk0MzUzfQ.0y5qnOVRVUdvV4Xwpqc9Sl2n_kLKlCEoebKZjNLFWKw
